modules/advert/models/Advert.php
<?php

namespace app\modules\advert\models;

use Yii;

use yii\db\Query;
use app\modules\advert\components\UploadFileBehavior;
use yii\web\UploadedFile;


/**
 * This is the model class for table "adverts".
 *
 * @property int $id
 * @property int $model_id
 * @property int $mileage
 * @property string $price
 * @property string $phone
 */
class Advert extends \yii\db\ActiveRecord
{

    public $brand;
    public $model;
    public $opt;
    public $images;
    public $option;

    const SCENARIO_CREATE = 'create';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'adverts';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [[ 'price', 'phone', 'mileage', 'brand', 'model_id', 'option'], 'required'],
            [['price', 'phone'], 'string', 'max' => 255],
            [['mileage'], 'integer'],
            [['images'], 'file', 'extensions'=>'jpg, jpeg, png', 'maxFiles' => 3, 'maxSize' => 2*1024*1024],
            [['status'], 'default', 'value' => 1 ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImages()
    {
       return Image::find()->where(['advert_id' => $this->id])->all();
    }

    public function getModel()
    {
        return Model::find()->where(['id' => $this->model_id])->one();
    }

    /**
     * @return yii\db\ActiveQuery
     */
    public function getOptions()
    {
        return $this->hasMany(Option::className(),['id' => 'option_id'])->viaTable('adverts_options', ['advert_id' => 'id']);
    }

    /**
     * @param null $object
     * @return int
     * @throws \yii\db\Exception
     */
    public function destroyOptions($object = null)
    {
        if ($object === null) $object = $this;
        return Yii::$app->db->createCommand()->delete('adverts_options', "advert_id = $object->id")->execute();
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'model_id' => 'Model ID',
            'mileage' => 'Mileage',
            'price' => 'Price',
            'phone' => 'Phone',
        ];
    }

    public function behaviors()
    {
        return[
             [
                'class' => 'app\modules\advert\components\StorageBehavior',
                'fileImages' => 'images',
                 'width' => 720,
                 'height' => 520,
            ]];

    }

    public function saveA()
    {
        $this->save();
        $query = new Query();

        foreach ($this->path as $path){
            $image = new Image();
            $image->advert_id = $this->id;
            $image->path = $path;
            $image->save();
        }

        foreach($this->option as $value) {
            $query->createCommand()->insert('adverts_options', [
                'advert_id' => $this->id,
                'option_id' => $value,
            ])->execute();
        }

        return true;
    }

    public function updateA()
    {
        $this->save();
        $query = new Query();
        if(!empty($this->path)) {
            $images = Image::findAll(['advert_id' => $this->id]);

            $i = 0;
            if(count($images) > count($this->path)){
                foreach ($images as $key => $img) {
                    $img->delete();
                    if (count($images) - $i == count($this->path)) exit;
                }
            }
            foreach ($this->path as $key => $path){
                if(!empty($images[$key])) {
                    $images[$key]->path = $path;
                    $images[$key]->advert_id = $this->id;
                    $images[$key]->save();
                }else{
                    $images = new Image();
                    $images->path = $path;
                    $images->advert_id = $this->id;
                    $images->save();
                }
            }

        }

        $this->destroyOptions();
        foreach($this->option as $value) {
            $query->createCommand()->insert('adverts_options', [
                'advert_id' => $this->id,
                'option_id' => $value,
            ])->execute();
        }

        return true;
    }

    public function deleteA()
    {
        $this->destroyOptions();
        $this->delete();
        Image::deleteAll(['advert_id' => $this->id]);
    }
}

modules/advert/controllers/AdvertController.php
<?php

namespace app\modules\advert\controllers;

use app\modules\advert\models\Brand;
use app\modules\advert\models\Image;
use app\modules\advert\models\Model;
use app\modules\advert\models\Option;
use Yii;
use app\modules\advert\models\Advert;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\helpers\ArrayHelper;
use yii\data\Pagination;


/**
 * AdvertController implements the CRUD actions for Advert model.
 */
class AdvertController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Advert models.
     * @return mixed
     */
    public function actionIndex()
    {

        $query = Advert::find()->where(['status' => 1]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 5]);
        $models = $query->offset($pages->offset)->limit($pages->limit)->all();

        return $this->render('index', [
            'models' => $models,
            'pages' => $pages,
        ]);
    }

    /**
     * Displays a single Advert model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $advert = Advert::find()->where(['id' => $id])->one();
        return $this->render('view', [
            'advert' => $advert,
        ]);
    }

    /**
     * Creates a new Advert model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $advert = new Advert();
        $brands = ArrayHelper::map(Brand::find()->all(), 'id', 'name');
        $models = ArrayHelper::map(Model::find()->where(['brand_id' => key($brands)])->all(),'id','name');
        $options =  ArrayHelper::map(Option::find()->all(), 'id', 'name');

        if ($advert->load(Yii::$app->request->post()) && $advert->saveA()) {
            return $this->redirect(['view', 'id' => $advert->id]);
        }

        return $this->render('create', [
            'advert' => $advert,
            'brands' => $brands,
            'options' => $options,
            'models' => $models,
        ]);
    }

    /**
     * Updates an existing Advert model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {

        $advert = Advert::find()->where(['id' => $id])->one();
        $model = Model::find()->where(['id' => $advert->model_id])->one();
        $brand = ArrayHelper::map(Brand::find()->all(), 'id', 'name');
        $option =  ArrayHelper::map(Option::find()->all(), 'id', 'name');
        $advert->option =$advert->options;
        $advert->brand = $model->brand->id;
        $advert->images = $advert->getImages();


        if ($advert->load(Yii::$app->request->post()) && $advert->updateA()) {
            return $this->redirect(['view', 'id' => $advert->id]);
        }

        return $this->render('update', [
            'advert' => $advert,
            'option' => $option,
            'brand' => $brand,
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Advert model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $advert =  Advert::find(['id' => $id])->one();
        $advert->deleteA();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Advert model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Advert the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Advert::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    public function actionModels()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if (Yii::$app->request->isAjax) {
            $id = Yii::$app->request->post('key');
            $models = Model::find()->where(['brand_id' => $id])->select('id, name')->all();
            return $models;
        }
    }

    /**
     * @param $adverts
     * @return $data array
     */
    private function prepareDataAll($adverts)
    {

        foreach ($adverts as $advert)
        {
            $model = Model::find()->where(['id' => $advert->model_id])->one();

            $brand = $model->brand;
            $data[] =[
                'id' => $advert->id,
                'price' => $advert->price,
                'image' => $advert->images[0]->path,
                'brand' => $model->brand->name,
                'model' => $model->name
            ];

        }

        return $data;
    }

    /**
     * @param $advert | Advert
     * @return array
     */
    private function prepareDataOne($advert)
    {
            $model = Model::find()->where(['id' => $advert->model_id])->one();
            $brand = $model->brand;

            $option = function ($advert, $param, $key) {
                foreach ($advert->$param as $value){
                    $data[] = $value->$key;
                }
                return !empty($data) ? $data : null;
            };

            $data =[
                'id' => $advert->id,
                'price' => $advert->price,
                'image' => $option($advert, 'images', 'path'),
                'options' => $option($advert, 'options', 'name'),
                'brand' => $model->brand->name,
                'model' => $model->name
            ];

        return $data;
    }
}

modules/advert/views/advert/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\modules\advert\models\Brand;
use app\modules\advert\assets\AdvAsset;

AdvAsset::register($this);
/* @var $this yii\web\View */
/* @var $advert app\modules\advert\models\Advert */
/* @var $brand app\modules\advert\models\Brand */
/* @var $options app\modules\advert\models\Option*/
/* @var $image app\modules\advert\models\Image*/

/* @var $form yii\widgets\ActiveForm */
?>
<?php

if($advert->hasErrors()){
    echo '<pre>';
    print_r($advert->getErrors());
    echo '</pre>';
}
?>

<div class="advert-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($advert, 'brand')->dropDownList($brands)->label('Brands') ?>

    <?= $form->field($advert, 'model_id')->dropDownList($models)->label('Model') ?>

    <?= $form->field($advert, 'option')->checkboxList($options); ?>

    <?= $form->field($advert, 'mileage')->textInput() ?>

    <?= $form->field($advert, 'price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($advert, 'phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($advert, 'images[]')->fileInput(['multiple' => true, 'accept' => 'image/*']) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/advert/views/advert/_form_update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use app\modules\advert\models\Brand;
use app\modules\advert\assets\AdvAsset;

AdvAsset::register($this);
/* @var $this yii\web\View */
/* @var $advert app\modules\advert\models\Advert */
/* @var $brand app\modules\advert\models\Brand */
/* @var $options app\modules\advert\models\Option*/
/* @var $image app\modules\advert\models\Image*/
/* @var $model app\modules\advert\models\Model*/
/* @var $form yii\widgets\ActiveForm */
?>

<?php
/*echo '<pre>';
print_r($brands);
die;*/
?>
<?php
/*echo '<pre>';
print_r(ArrayHelper::map($options->find()->all(),'id','name'));
print_r($checkedOptions );

die;*/

?>

<div class="advert-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($advert, 'brand')->dropDownList($brand)->label('Brands') ?>

    <?= $form->field($advert, 'model_id')->dropDownList([$model->id => $model->name])->label('Model') ?>

    <?= $form->field($advert, 'option')->checkboxList($option); ?>

    <?= $form->field($advert, 'mileage')->textInput() ?>

    <?= $form->field($advert, 'price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($advert, 'phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($advert, 'images[]')->fileInput(['multiple' => true, 'accept' => 'image/*']) ?>

   <?php if(!empty($advert->images)){
            foreach ($advert->images as $image) {
                echo Html::img('/uploads/' .$image->path, $options = ['class' => 'img-thumbnail', 'style' => ['width' => '146px', 'height' => '106']]);
            }
        }
    ?>
    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>


</div>

modules/advert/views/advert/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $brands array app\modules\advert\models\Brand */
/* @var $advert app\modules\advert\models\Advert */
/* @var $options app\modules\advert\models\Option*/


$this->title = 'Create Advert';
$this->params['breadcrumbs'][] = ['label' => 'Adverts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="advert-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'advert' => $advert,
        'brands' => $brands,
        'models' => $models,
        'options' => $options,
    ]) ?>

</div>

modules/advert/views/advert/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\LinkPager;
use Yii;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $data array mixed (Advert, Image, Options, Brand, Model) */
/* @var  $pages yii\data\Pagination*/

$this->title = 'Adverts';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="advert-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Advert', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php foreach ($models as $advert): ?>

    <div class="panel panel-default" >

        <div class="panel-body" >
            <div style="display: inline-block">
                <?php if(!empty($advert->getImages()[0])): ?>
                <?= Html::img('/uploads/' .$advert->getImages()[0]->path, $options = ['class' => 'img-thumbnail', 'style' => ['width' => '146px', 'height' => '106']]); ?>
               <?php else: ?>
               <?php echo 'Нет картинки' ?>
               <?php endif; ?>
               <h3 style="display: inline-block";>
                <?= Html::a($advert->getModel()->brand->name . '  '. $advert->getModel()->name, ['advert/view', 'id' => $advert->id, ['class' => 'profile-link']]) ?>
               </h3>
            <h4 style="display: inline-block">
                <?= Yii::$app->formatter->asCurrency($advert->price) ?>
            </h4>
        <div style="display: inline-block">
            <?= Html::beginForm(['advert/delete', 'id' => $advert->id, 'post', ['style' => 'display: inline-block']]) ?>
            <?= Html::submitButton('Delete', ['class' => 'btn btn-warning', 'style' => 'display: inline-block']) ?>
            <?= Html::endForm() ?>
        </div>
        </div>
        </div>
    </div>

    <?php endforeach; ?>

</div>

<?= LinkPager::widget([
    'pagination' =>  $pages,
]);
?>

modules/advert/views/advert/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $brands array app\modules\advert\models\Brand */
/* @var $advert app\modules\advert\models\Advert */
/* @var $brand app\modules\advert\models\Brand */
/* @var $options app\modules\advert\models\Option*/
/* @var $image app\modules\advert\models\Image*/


$this->title = 'Update Advert: ' . $advert->id;
$this->params['breadcrumbs'][] = ['label' => 'Adverts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $advert->id, 'url' => ['view', 'id' => $advert->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="advert-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form_update', [
        'advert' => $advert,
        'brand' => $brand,
        'model' => $model,
        'option' => $option,
    ]) ?>

</div>

modules/advert/views/advert/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\modules\advert\models\Advert */

$this->title = $advert->getModel()->brand->name . ' ' . $advert->getModel()->name;
$this->params['breadcrumbs'][] = ['label' => 'Adverts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="advert-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $advert->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $advert->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

   <div class="container">
       <div class="row">
           <div class="col-md-6 col-lg-6" >
               <?php if(!empty($advert->getImages()[0])): ?>
               <?= Html::img('/uploads/' . $advert->getImages()['0']->path, $options = ['class' => 'img-thumbnail', 'style' => ['width' => '720px', 'height' => '540']]); ?>
               <?php
                foreach ($advert->getImages() as $image){
                    echo Html::img('/uploads/' . $image->path, $options = ['class' => 'img-thumbnail', 'style' => ['width' => '146px', 'height' => '106']]);
                }
               ?>
               <?php else: ?>
                    <h3>
                        Нет изображения
                    </h3>
               <?php endif ?>
           </div>
           <div class="col-md-6 col-lg-6" >
               <p>Бренд: <?= $advert->getModel()->brand->name ?></p>
               <p>Модель: <?= $advert->getModel()->name ?></p>
               <p>Опции:
                   <?php
                    if(!empty($advert->options)){
                        foreach ($advert->options as $option){
                            echo $option->name . '    ';
                        }
                        }else{
                        echo 'Без опций';
                    }
                   ?>
               </p>
               <p>Цена: <?= $advert['price'] ?></p>
           </div>
       </div>
   </div>




    <?php /* DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'model_id',
            'mileage',
            'price',
            'phone',
        ],
    ])*/ ?>

</div>